// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApi.Database;

#nullable disable

namespace WebApi.Migrations
{
    [DbContext(typeof(RateLimiteDbContext))]
    [Migration("20240104221546_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("WebApi.Model.Client", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Identifier")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("RateLimitId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("RateLimitId");

                    b.ToTable("Clients");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Identifier = "client1",
                            RateLimitId = 1L
                        },
                        new
                        {
                            Id = 2L,
                            Identifier = "client2",
                            RateLimitId = 2L
                        },
                        new
                        {
                            Id = 3L,
                            Identifier = "client3",
                            RateLimitId = 3L
                        });
                });

            modelBuilder.Entity("WebApi.Model.RateLimit", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("PermitLimit")
                        .HasColumnType("INTEGER");

                    b.Property<int>("QueueLimit")
                        .HasColumnType("INTEGER");

                    b.Property<TimeSpan>("Window")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("RateLimits");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            PermitLimit = 1,
                            QueueLimit = 0,
                            Window = new TimeSpan(0, 0, 0, 1, 0)
                        },
                        new
                        {
                            Id = 2L,
                            PermitLimit = 2,
                            QueueLimit = 0,
                            Window = new TimeSpan(0, 0, 0, 1, 0)
                        },
                        new
                        {
                            Id = 3L,
                            PermitLimit = 3,
                            QueueLimit = 0,
                            Window = new TimeSpan(0, 0, 0, 1, 0)
                        });
                });

            modelBuilder.Entity("WebApi.Model.Client", b =>
                {
                    b.HasOne("WebApi.Model.RateLimit", "RateLimit")
                        .WithMany("Clients")
                        .HasForeignKey("RateLimitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RateLimit");
                });

            modelBuilder.Entity("WebApi.Model.RateLimit", b =>
                {
                    b.Navigation("Clients");
                });
#pragma warning restore 612, 618
        }
    }
}
